;;1 O(|xs|^2)
(define (list->set xs)
  (define (count x xs)
  (if(null? xs)
     0
     (if(equal? (car xs) x)
        (+ 1 (count x (cdr xs)))
        (count x (cdr xs))
        )
     )
  )
  (define (iter xs)
    (if(null? xs)
       xs
       (if(>= (count (car xs) (cdr xs)) 1)
          (iter (cdr xs))
          (cons (car xs) (iter (cdr xs)))
          )
       )
    )
  (iter xs)
  )
;;2 O(|xs|^2)
(define (set? xs)
  (define (count x xs)
  (if(null? xs)
     0
     (if(equal? (car xs) x)
        (+ 1 (count x (cdr xs)))
        (count x (cdr xs))
        )
     )
  )
  (define (iter xs)
      (or (null? xs) (and (= (count (car xs) xs) 1)
                          (iter (cdr xs))))
    )
  (iter xs)
  )
;;3 O((|xs|+|ys|)^2)
(define (union xs ys)
  (list->set (append xs ys))
  )
;;4 O(|xs|*|ys|) 
(define (intersection xs ys)
  (define (count x xs)
  (if(null? xs)
     0
     (if(equal? (car xs) x)
        (+ 1 (count x (cdr xs)))
        (count x (cdr xs))
        )
     )
  )
  (define (iter xs ys)
    (if(null? xs)
       xs
       (if(= (count (car xs) ys) 1)
          (cons (car xs) (intersection (cdr xs) ys))
          (intersection (cdr xs) ys)
          )
       )
    )
  (iter xs ys)
  )
;;5 O(|xs|*|ys|)
(define (difference xs ys)
  (define (count x xs)
  (if(null? xs)
     0
     (if(equal? (car xs) x)
        (+ 1 (count x (cdr xs)))
        (count x (cdr xs))
        )
     )
  )
  (define (iter xs ys)
    (if(null? xs)
       xs
       (if(= (count (car xs) ys) 0)
          (cons (car xs) (difference (cdr xs) ys))
          (difference (cdr xs) ys)
          )
       )
    )
  (iter xs ys)
  )
;;6 O((|xs|+|ys|)^2+2*|xs|*|ys|)
(define (symmetric-difference xs ys)
  (union (difference xs ys) (difference ys xs))
  )
;;7 O((|xs|+|ys|)^2+2*|xs|*|ys|)
(define (set-eq? xs ys)
  (null? (symmetric-difference xs ys))
  )
