;;1 O(|xs|)
(define (string-trim-left xs)
  (define (del_sp xs)
    (if(null? xs)
       '()
       (if(char-whitespace? (car xs))
          (del_sp (cdr xs))
          xs
          )
       )
    )
  (list->string (del_sp (string->list xs)))
  )
;;O(|xs|)
(define (string-trim-right xs)
  (list->string(reverse (string->list (string-trim-left (list->string(reverse
                                                         (string->list xs)))))))
  )
;;O(|xs|)
(define (string-trim xs)
  (string-trim-right (string-trim-left xs))
  )
;;O(min(|xs|, |ys|))
(define (string-prefix? xs ys)
  (define (iter xs ys)
    (if(null? xs)
       (null? xs)
       (if(null? ys)
          (not (null? ys))
          (if(equal? (car xs) (car ys))
             (iter (cdr xs) (cdr ys))
             (equal? (car xs) (car ys))
             )
          )
       )
    )
  (iter (string->list xs) (string->list ys))
  )
;;O(min(|xs|, |ys|))
(define (string-suffix? xs ys)
  (string-prefix?  (list->string(reverse (string->list xs)))
                   (list->string (reverse (string->list ys))))
  )
;;O(|ys|*min(|xs|, |ys|))
(define (string-infix? xs ys)
  (define (iter xs ys)
    (if(null? ys)
       (or (not (null? ys)) (null? xs))
       (if(string-prefix? (list->string xs) (list->string ys))
          (string-prefix? (list->string xs) (list->string ys))
          (iter xs (cdr ys))
          )
       )
    )
  (iter (string->list xs) (string->list ys))
  )
;;O(|xs|*min(|xs|, |sep|))
(define (string-split xs sep)
  (define (iter xs sep)
    (if(string-prefix? (list->string sep) (list->string xs))
       (let((len (length sep)))
         (define (del xs len)
           (if(= len 0)
              xs
              (del (cdr xs) (- len 1))
              )
           )
         (iter (del xs len) sep)
         )
       (if(null? xs)
          xs
          (cons (string(car xs)) (iter (cdr xs) sep))
          )
       )
    )
  (iter (string->list xs) (string->list sep))
  )
