(define (derivative expr)
  (if(not (pair? expr))
     (set! expr (list expr))
     )
  (define(element-func expr)
    (cond
      ((and (= (length expr) 1) (number? (car expr))) '0)
      ((and (= (length expr) 1) (equal? (car expr) 'x)) '1)
      ((and (= (length expr) 2) (equal? (car expr) '-) (equal? (cadr expr) 'x)) '-1)
      ((and (equal? (car expr) 'expt) (equal? (cadr expr) 'x)
            (number? (caddr expr)))
       `(* ,(caddr expr) (expt ,(cadr expr) ,(- (caddr expr) 1))))
      ((and (equal? (car expr) 'sin) (equal? (cadr expr) 'x)) `(cos x))
      ((and (equal? (car expr) 'cos) (equal? (cadr expr) 'x)) `(- (sin x)))
      ((and (equal? (car expr) 'exp)
            (equal? (cadr expr) 'x)) expr)
      ((and (equal? (car expr) 'log) (equal? (cadr expr) 'x)) `(/ 1 x))
      ((and (equal? (car expr) 'expt) (number? (cadr expr))
            (equal? (caddr expr) 'x)) `(* (expt ,(cadr expr) x) (log ,(cadr expr))))
      (else #f)
      )
    )
  (define (hard-func expr)
    (cond
      ((and (equal? (car expr) 'expt) (number? (caddr expr)))
       `(* ,(caddr expr) (expt ,(cadr expr)
                               ,(- (caddr expr) 1)) ,(derivative (cadr expr))))
      ((and (equal? (car expr) 'sin)) `(* ,(derivative (cadr expr)) (cos ,(cadr expr))))
      ((and (equal? (car expr) 'cos)) `(* ,(derivative (cadr expr)) (- (sin ,(cadr expr)))))
      ((and (equal? (car expr) 'exp))
       `(* ,expr ,(derivative (cadr expr))))
      ((and (equal? (car expr) 'log)) `(*  (/ 1 ,(cadr expr)) ,(derivative (cadr expr))))
      ((and (equal? (car expr) 'expt) (number? (cadr expr)))
       `(* (expt ,(cadr expr) x) (log ,(cadr expr)) ,(derivative (caddr expr))))
      (else expr)
      )
    )
  (define (mul expr)
    (define plus +)
    (if(equal? (car expr) '*)
       (if(= (length expr) 3)
          `(+ (* ,(derivative (cadr expr)) ,(caddr expr))
              (* ,(cadr expr) ,(derivative (caddr expr))))
          (list '+ (list '* (derivative (cadr expr)) (cons '* (cddr expr)))
                (list '* (cadr expr) (derivative (cons '* (cddr expr)))))
          )
       #f
       )
    )
  (define (sum expr)
    (if(and (or (equal? (car expr) '+) (equal? (car expr) '-)) (> (length expr) 2))
       `(,(car expr) ,(derivative (cadr expr)) ,(derivative (caddr expr)))
       #f
       )
    )
  (define (del expr)
    (if(equal? (car expr) '/)
       `(/ (- (* ,(derivative (cadr expr)) ,(caddr expr))
              (* ,(cadr expr) ,(derivative (caddr expr))))
           (expt ,(caddr expr) 2)
           )
       #f
       )
    )
  (or
   (element-func expr)
   (mul expr)
   (sum expr)
   (del expr)
   (hard-func expr)
   )
  )
