(define (read-words)
  (let((f (read-char))
       (last 0)
       (words '())
       (cur-word ""))
    (define (reader f)
      (if(eof-object? f)
         (let()
           (if(= last 1)
              (begin
                (set! words (append words (list cur-word)))
                )
              )
           words
           )
         (let()
           (cond
             ((not(char-whitespace? f))
              (let()
                (set! last 1)
                (set! cur-word (string-append cur-word (string f)))
                )
              )
             ((= last 1)
              (begin
                (set! last 0)
                (set! words (append words (list cur-word)))
                (set! cur-word "")
                )
              )
             )
           (reader (read-char))
           )
         )
      )
    (reader f)
    )
  )
