(define-syntax define-struct
  (syntax-rules()
    ((define-struct name args)
     (let((make-name
           (string->symbol (string-append "make-" (symbol->string 'name))))
          (name? (string->symbol (string-append (symbol->string 'name) "?"))))
       (define (iter argv)
         (if(not(null? argv))
            (let((refi (string->symbol (string-append (symbol->string 'name) "-" 
                                                   (symbol->string (car argv)))))
                 (seti (string->symbol (string-append "set-" (symbol->string 'name) "-" 
                                                   (symbol->string (car argv)) "!"))))
              (eval `(define (,refi pos-name)
                       (cadr (assoc (quote ,(car argv)) (cdr pos-name)))
                       )
               (interaction-environment))
              (eval `(define (,seti pos-name new-el)
                       (set-car! (cdr (assoc (quote ,(car argv)) (cdr pos-name))) new-el)
                       )
                    (interaction-environment))
              (iter (cdr argv))
              )
            )
         )
       (iter 'args)
       (eval `(define (,make-name . ar)
         (cons 'name (apply map list (list 'args ar)))
         ) (interaction-environment))
       (eval `(define (,name? obj)
                (and (list? obj) (not(null? obj))
                     (equal? (car obj) 'name))
                )
             (interaction-environment))
       (iter 'args)
       )))
  )
