(define (my-gcd a b)
  (if(= (min a b) 0)
     (max (abs a) (abs b))
     (my-gcd (min (abs a) (abs b)) (remainder (max (abs a) (abs b)) (min (abs a) (abs b))))
     )
  )
(define (my-lcm a b)
  (/ (* (abs a) (abs b)) (my-gcd a b))
  )
(define (prime? n)
  (define (iter c)
    (if(> c (sqrt (abs n)))
       (> c (sqrt (abs n)))
       (if(= (remainder (abs n) c) 0)
          (not (= (remainder (abs n) c) 0))
          (iter (+ c 1))
          )
       )
    )
  (if(= (abs n) 1)
     (not (= (abs n) 1))
     (iter 2)
     )
  )
