;;1
(define-syntax trace
  (syntax-rules()
    ((trace xs)
     (let ((dop xs))
       (write 'xs)
       (display " => ")
       (write dop)
       (newline)
       dop))           
    )
  )
;;2
(define-syntax test
  (syntax-rules()
    ((test res etalon) '(res etalon))
    )
  )
(define (run-test xs)
  (write (car xs))
  (define func-res (eval (car xs) (interaction-environment)))
  (if(equal? func-res (cadr xs))
     (let ((res (equal? func-res (cadr xs))))
       (display " ok\n")
       res)
     (let ((res (equal? func-res (cadr xs))))
       (display " FAIL\n")
       (display "  Expected: ")
       (write (cadr xs))
       (newline)
       (display "  Returned: ")
       (write func-res)
       (newline)
       res)))
(define (run-tests tests)
  (if(null? (cdr tests))
     (run-test (car tests))
     ((lambda (x y)
        (and x y))
      (run-test (car tests))
      (run-tests (cdr tests))
      ))
  )
;;3
(define(reverse! . xss)
  ;;help-functions
  (define (list-set! a index new_el n)
    (if(null? a)
       '()
       (if(= n index)
          (set-car! a new_el)
          (list-set! (cdr a) index new_el (+ n 1)))))
  (define (type-length a)
    (cond
      ((string? a) (string-length a))
      ((vector? a) (vector-length a))
      ((list? a) (length a))
      )
    )
  (define (type-ref a index)
    (cond
      ((string? a) (string-ref a index))
      ((vector? a) (vector-ref a index))
      ((list? a) (list-ref a index))
      )
    )
  (define (type-set! a index new_el)
    (cond
      ((string? a)
       (string-set!  a index (if(integer? new_el)
                                (string-ref (number->string new_el) 0)
                                (if(symbol? new_el)
                                   (string-ref (symbol->string new_el) 0)
                                   new_el))))

      ((vector? a) (vector-set! a index new_el))
      ((list? a) (list-set! a index new_el 0))
      )
    )
  (define (type->list xs)
    (if(string? xs)
       (string->list xs)
       (if(vector? xs)
          (vector->list xs)
          xs)
       )
    )
  ;;main
  (if(= (length xss) 2)
     (let((xs (car xss)))
       (define receiver (cadr xss))
       (if(equal? xs receiver)
          (reverse! xs)
          (let()
            (define len (type-length xs))
            (do((i 0 (+ i 1)))
              ((<= len i))
              (let()
                (type-set! receiver i (type-ref xs (- len i 1)))))
            )
          )
       )
     (let((xs (car xss)))
       (let((len (type-length xs)))
         (do((i 0 (+ i 1)))
           ((<= (/ len 2) i))
           (let()
             (define dop (type-ref xs i))
             (type-set! xs i (type-ref xs (- len i 1)))
             (type-set! xs (- len i 1) dop)
             )
           ))
       )
     )
  )

(define the-tests
  (list
   (test
    (let()
      (define xs '(a b c d e))
      (reverse! xs)
      xs)
    (e d c b a)
    )
   (test
    (let()
      (define ys (string #\h#\e#\l#\l#\o))
      (reverse! ys)
      ys)
    "olleh"
    )
   (test
    (let()
      (define zs (vector 1 2 3 4 5))
      (reverse! zs)
      zs)
    #(5 4 3 2 1)
    )
   (test
    (let()
      (define xs '(a b c d e))
      (define zs (vector 1 2 3 4 5))
      (reverse! xs zs)
      (list xs zs)
      )
    ((a b c d e) #(e d c b a))
    )
   (test
    (let()
      (define ys (string #\h#\e#\l#\l#\o))
      (define zs (vector 1 2 3 4 5))
      (reverse! ys zs)
      zs
      )
    #(#\o #\l #\l #\e #\h)
    )
   (test
    (let()
      (define ys (string #\h#\e#\l#\l#\o))
      (reverse! ys ys)
      ys
      )
    "olleh"
    )
   (test
    (let()
      (define zs #(1 2 3 4 5))
      (define xs '(a b c d e))
      (reverse! zs xs)
      xs
      )
    (5 4 3 2 1)
    )
   (test
    (let()
      (define xs '(1 2))
      (define ys (string #\h#\i))
      (reverse! xs ys)
      ys
      )
    "21")
   (test
    (let()
      (define xs '(a b c d e))
      (define ys (string #\h#\e#\l#\l#\o))
      (reverse! xs ys)
      ys
      )
    "edcba")
   )
  )
  

(run-tests the-tests)
;;4
(define (factorize xs)
  (define op (car xs))
  (define sl1 (cadr xs))
  (define sl2 (caddr xs))
  (define a (cadr (cadr xs)))
  (define b (cadr (caddr xs)))
  (if(and (equal? op '-) (equal? (caddr sl1) '2) (equal? (caddr sl2) '2))
     `(* (- ,a ,b) (+ ,a ,b))
     (if(and (equal? op '-) (equal? (caddr sl1) '3) (equal? (caddr sl2) '3))
         `(* (- ,a ,b) (+ (expt ,a 2) (* ,a ,b) (expt ,b 2)))
         `(* (+ ,a ,b) (+ (expt ,a 2) (- (* ,a ,b)) (expt ,b 2)))
     )
  )
  )
(define the-tests
  (list
   (test (factorize '(- (expt x 2) (expt y 2)))
         (* (- x y) (+ x y)))
   (test (factorize '(- (expt (+ first 1) 2) (expt (- second 1) 2)))
         (* (- (+ first 1) (- second 1)) (+ (+ first 1) (- second 1))))
   (test (eval (list (list 'lambda'(x y) (factorize '(- (expt x 2) 
                        (expt y 2)))) 1 2) (interaction-environment)) -3)
   (test (factorize '(- (expt x 3) (expt y 3)))
         (* (- x y) (+ (expt x 2) (* x y) (expt y 2))))
   (test (factorize '(- (expt (+ a b c) 2) (expt (- d e f) 2)))
         (* (- (+ a b c) (- d e f)) (+ (+ a b c) (- d e f))))
   (test (factorize '(+ (expt x 3) (expt y 3)))
         (* (+ x y) (+ (expt x 2) (- (* x y)) (expt y 2))))
   (test (eval (list (list 'lambda'(x y) (factorize '(+ (expt x 3) 
                        (expt y 3)))) 3 2) (interaction-environment)) 35)
   (test (eval (list (list 'lambda'(x y) (factorize '(- (expt x 3) 
                        (expt y 3)))) 5 4) (interaction-environment)) 61)
   ))
(run-tests the-tests)
