;;1. Продолжения.
(define loc #f)
(define (use-assertions)
  (call-with-current-continuation (lambda (x) (set! loc x))))

(define-syntax assert
  (syntax-rules ()
    ((assert usl)
     (if(not usl)
        (let()
          (display "FAILED: ")
          (write 'usl)
          (loc)
          )
        )
     )
    )
  )
(use-assertions)

;;2. Код как данные. Порты ввода-вывода.
;;Поиск рекурсивных функций
(define (select-rec source dest)
  (define (my-flatten xs)
    (if(null? xs)
       xs
       (if(list? (car xs))
          (append (my-flatten (car xs)) (my-flatten (cdr xs)))
          (cons (car xs) (my-flatten (cdr xs)))
          )
       )
    )
  (define (iter xs)
    (and
       (not(or (null? xs) (not (equal? (car xs) 'define))))
       (let((name (cadr (my-flatten xs)))
            )
         (define (find? ys)
           (and
              (not(null? ys))
              (if(equal? (car ys) name)
                 (begin
                   (display xs)
                   (newline)
                   )
                 (find? (cdr ys)) 
                 )
              )
           )
         (find? (cddr (my-flatten xs)))
         )
       )
    )
  (with-output-to-file dest
    (lambda ()
      (let()
        (with-input-from-file source
          (lambda ()
            (let((f (read)))
              (define (reader f)
                (if(not(eof-object? f))
                   (let()
                     (iter f)
                     (reader (read))
                     )
                   )
                )
              (reader f)
              )
            )
          )
        )
      )
    )
  )
;;анализ текста
(define (text-start source)
  (with-input-from-file source
    (lambda()
      (let((f (read-char)))
        (define (char-math? a)
          (or
           (equal? a #\=)
           (equal? a #\+)
           (equal? a #\-)
           (equal? a #\\)
           (equal? a #\))
           (equal? a #\()
           (equal? a #\*)
           (equal? a #\^)
           )
          )
        (define itog '(0 0 0)) ;;формула числа слова 
        (define last '(0 0)) ;; числа буквы
        (define (iter f)
          (if(not (eof-object? f))
             (if(or (char-whitespace? f) (and (not (char-numeric? f))
                                              (not (char-alphabetic? f))
                                              (not (char-math? f))
                                              ))
                (let()
                  (cond
                    ((> (* (car last) (cadr last)) 0)
                     (set! itog (list (+ (car itog) 1) (cadr itog) (caddr itog))))
                    ((> (car last) 0)
                     (set! itog (list (car itog) (+ (cadr itog) 1) (caddr itog))))
                    ((> (cadr last) 0)
                     (set! itog (list (car itog) (cadr itog) (+ (caddr itog) 1))))
                    )
                  (set! last '(0 0))
                  (iter (read-char))
                  )
                (let()
                  (cond
                    ((char-numeric? f)
                     (set! last (list (+ (car last) 1) (cadr last))))
                    ((char-math? f)
                     (set! last (list (+ (car last) 1) (+ (cadr last) 1))))
                    (else
                     (set! last (list (car last) (+ (cadr last) 1))))
                    )
                  (iter (read-char))
                  )
                )
             (let()
               (cond
                 ((> (* (car last) (cadr last)) 0)
                  (set! itog (list (+ (car itog) 1) (cadr itog) (caddr itog))))
                 ((> (car last) 0)
                  (set! itog (list (car itog) (+ (cadr itog) 1) (caddr itog))))
                 ((> (cadr last) 0)
                  (set! itog (list (car itog) (cadr itog) (+ (caddr itog) 1))))
                 )
               )
             )
          )
        (iter f)
        (display "Кол-во слов: ")
        (display (caddr itog))
        (newline)
        (display "Кол-во чисел: ")
        (display (cadr itog))
        (newline)
        (display "Кол-во формул: ")
        (display (car itog))
        )
      )
    )
  )
;;3 Мемоизация результатов вычисления.
;;с мемоизацией
(define t-with-memois
  (let ((known-results '()))
    (lambda (n)
      (let* ((args (list n))
             (res (assoc args known-results)))
        (if res
            (cadr res)
            (let ((res 
                   (let()
                     (cond
                       ((<= n 1) 0)
                       ((= n 2) 1)
                       (else (+ (t-with-memois (- n 1))
                                (t-with-memois (- n 2))
                                (t-with-memois (- n 3))))
                       )
                     )
                   ))
              (set! known-results (cons (list args res) known-results))
              res))))))
;;без мемоизации
(define (t n)
  (cond
    ((<= n 1) 0)
    ((= n 2) 1)
    (else (+ (t (- n 1)) (t (- n 2)) (t (- n 3))))
    )
  )
  
;; 4. Оложенные вычисления
(define-syntax lazy-cons
  (syntax-rules()
    ((lazy-cons a b) (cons a (delay  b)))
    ))
(define (lazy-car p)
  (car p)
  )
(define (lazy-cdr p)
  (force (cdr p))
  )
(define (lazy-head xs k)
  (if(= k 0)
     '()
     (cons (lazy-car xs) (lazy-head (lazy-cdr xs) (- k 1)))
     )
  )
(define (lazy-ref xs k)
  (if(= k 0)
     (lazy-car xs)
     (lazy-ref (lazy-cdr xs) (- k 1))
     )
  )
(define (lazy-map proc xs)
  (lazy-cons (proc (lazy-car xs)) (lazy-map proc (lazy-cdr xs)))
  )
(define (lazy-zip xs ys)
  (lazy-cons (list (lazy-car xs) (lazy-car ys))
             (lazy-zip (lazy-cdr xs) (lazy-cdr ys)))
  )
;;Ленивый список факториалов
(define (naturals start)
  (lazy-cons start (naturals (+ start 1)))
  )
(define (factorials start)
  (lazy-cons start (lazy-map (lambda (x) (* (car x) (cadr x)))
                             (lazy-zip (naturals 2) (factorials 1))))
  )

5. Управляющие конструкции.
;;A
(define-syntax unless
  (syntax-rules()
    ((uless cond? . exprs)
     (let()
       (if(not cond?)
          (let() . exprs))
       )
     )
    )
  )
;;B
(define-syntax while
  (syntax-rules()
    ((while cond? . exprs)
     (let iter()
       (if cond?
          (let() (let() . exprs) (iter))
          )
       )
     )
    )
  )
;;Д
(define-syntax cout
  (syntax-rules(<< endl)
    ((cout << endl) (newline))
    ((cout << exprs) (display exprs))
    ((cout << endl . others)
     (let()
       (newline)
       (cout . others)
       ))
    ((cout << expr . others)
     (let()
       (display expr)
       (cout . others)
       ))
    )
  )
 
