(define (interpret code stack)
  (define (iter code stack words)
    (if(not(null? code))
       (if(number? (car code))
          (iter (cdr code) (cons (car code) stack) words)
          (cond
            ((and (equal? (car code) 'neg))
             (iter (cdr code) (cons (- (car stack)) (cdr stack)) words))
            ((equal? (car code) '-)
             (iter (cdr code) (cons (- (cadr stack) (car stack)) (cddr stack)) 
             words))
            ((equal? (car code) '+)
             (iter (cdr code) (cons (+ (cadr stack) (car stack)) (cddr stack)) 
             words))
            ((equal? (car code) '*)
             (iter (cdr code) (cons (* (cadr stack) (car stack)) (cddr stack)) 
             words))
            ((equal? (car code) '/)
             (iter (cdr code) (cons (/ (cadr stack) (car stack)) (cddr stack)) 
             words))
            ((equal? (car code) 'mod)
             (iter (cdr code) (cons (remainder (cadr stack) (car stack)) 
             (cddr stack)) words))
            ((equal? (car code) '=)
             (cond
               ((equal? (car stack) (cadr stack)) (iter (cdr code) 
                    (append '(-1) (cddr stack)) words))
               (else (iter (cdr code) (append '(0) (cddr stack)) words))
               )
             )
            ((equal? (car code) '>)
             (cond
               ((> (cadr stack) (car stack)) (iter (cdr code) (append '(-1)
                (cddr stack)) words))
               (else (iter (cdr code) (append '(0) (cddr stack)) words))
               ))
            ((equal? (car code) '<)
             (cond
               ((< (cadr stack) (car stack)) (iter (cdr code) (append '(-1) 
               (cddr stack)) words))
               (else (iter (cdr code) (append '(0) (cddr stack)) words))
               )
             )
            ((equal? (car code) 'not)
             (cond
               ((equal? (car stack) '0)
                (iter (cdr code) (append '(-1) (cdr stack)) words))
               (else (iter (cdr code) (append '(0) (cdr stack)) words))
               )
             )
            ((equal? (car code) 'and)
             (cond
               ((or (equal? (car stack) '0) (equal? (cadr stack) '0))
                (iter (cdr code) (append '(0) (cddr stack)) words))
               (else (iter (cdr code) (append '(-1) (cddr stack)) words))
               )
             )
            ((equal? (car code) 'or)
             (cond
               ((and (equal? (car stack) '0) (equal? (cadr stack) '0))
                (iter (cdr code) (append '(0) (cddr stack)) words))
               (else (iter (cdr code) (append '(-1) (cddr stack)) words))
               )
             )
            ((equal? (car code) 'drop)
             (iter (cdr code) (cdr stack) words)
             )
            ((equal? (car code) 'swap)
             (iter (cdr code) (append (list (cadr stack)) (list (car stack)) 
             (cddr stack)) words)
             )
            ((equal? (car code) 'dup)
             (iter (cdr code) (cons (car stack) stack) words)
             )
            ((equal? (car code) 'over)
             (iter (cdr code) (cons (cadr stack) stack) words)
             )
            ((equal? (car code) 'rot)
             (iter (cdr code) (append (list (caddr stack)) (list (cadr stack))
                                      (list (car stack)) (cdddr stack)) words)
             )
            ((equal? (car code) 'depth)
             (iter (cdr code) (cons (length stack) stack) words)
             )
            ((equal? (car code) 'define)
             (let((name-state (cadr code)))
               (define (read-code code code-state)
                 (if(equal? (car code) 'end)
                    (iter (cdr code) stack (append words (list 
                    (list name-state code-state))))
                    (read-code (cdr code) (append code-state (list (car code))))
                    ))
               (read-code (cddr code) '())
               )
             )
            ((equal? (car code) 'exit)
             (let ()
               (define (skip code)
                 (if (equal? (car code) 'end)
                     (iter (cdr code) stack words)
                     (skip (cdr code))
                     )
                 )
               (skip code)
               ))
            ((equal? (car code) 'if)
             (if(equal? (car stack) 0)
                (let()
                  (define (skip code)
                    (if(equal? (car code) 'endif)
                       (iter (cdr code) (cdr stack) words)
                       (skip (cdr code))
                       )
                    )
                  (skip code)
                  )
                (let()
                  (define (use-code code use)
                    (if(equal? (car code) 'endif)
                       (iter  (append use (cdr code)) (cdr stack) words)
                       (use-code (cdr code) (append use (list (car code))))
                       )
                    )
                  (use-code (cdr code) '())
                  )
                )
             )
            ((assoc (car code) words)
             (iter (append (append (cadr (assoc (car code) words)) '(end)) 
             (cdr code)) stack words) 
             )
            ((equal? (car code) 'end)
             (iter (cdr code) stack words))
            )
          )
       stack
       )
    )
  (iter (vector->list code) stack '())
  )
